/**
 * Error codes and the EidolonError type.
 * Every expected failure in the system maps to one of these codes.
 */

export const ErrorCode = {
  // Config
  CONFIG_NOT_FOUND: "CONFIG_NOT_FOUND",
  CONFIG_INVALID: "CONFIG_INVALID",
  CONFIG_PARSE_ERROR: "CONFIG_PARSE_ERROR",
  // Secrets
  SECRET_NOT_FOUND: "SECRET_NOT_FOUND",
  SECRET_DECRYPTION_FAILED: "SECRET_DECRYPTION_FAILED",
  MASTER_KEY_MISSING: "MASTER_KEY_MISSING",
  // Database
  DB_CONNECTION_FAILED: "DB_CONNECTION_FAILED",
  DB_MIGRATION_FAILED: "DB_MIGRATION_FAILED",
  DB_QUERY_FAILED: "DB_QUERY_FAILED",
  // Claude
  CLAUDE_NOT_INSTALLED: "CLAUDE_NOT_INSTALLED",
  CLAUDE_AUTH_FAILED: "CLAUDE_AUTH_FAILED",
  CLAUDE_RATE_LIMITED: "CLAUDE_RATE_LIMITED",
  CLAUDE_PROCESS_CRASHED: "CLAUDE_PROCESS_CRASHED",
  CLAUDE_TIMEOUT: "CLAUDE_TIMEOUT",
  // Sessions
  SESSION_NOT_FOUND: "SESSION_NOT_FOUND",
  SESSION_LIMIT_REACHED: "SESSION_LIMIT_REACHED",
  // Memory
  MEMORY_EXTRACTION_FAILED: "MEMORY_EXTRACTION_FAILED",
  EMBEDDING_FAILED: "EMBEDDING_FAILED",
  // Channel
  CHANNEL_AUTH_FAILED: "CHANNEL_AUTH_FAILED",
  CHANNEL_SEND_FAILED: "CHANNEL_SEND_FAILED",
  // Gateway
  GATEWAY_AUTH_FAILED: "GATEWAY_AUTH_FAILED",
  // GPU
  GPU_UNAVAILABLE: "GPU_UNAVAILABLE",
  GPU_AUTH_FAILED: "GPU_AUTH_FAILED",
  TTS_FAILED: "TTS_FAILED",
  STT_FAILED: "STT_FAILED",
  // Notifications
  APNS_AUTH_FAILED: "APNS_AUTH_FAILED",
  APNS_SEND_FAILED: "APNS_SEND_FAILED",
  APNS_DEVICE_UNREGISTERED: "APNS_DEVICE_UNREGISTERED",
  APNS_RATE_LIMITED: "APNS_RATE_LIMITED",
  // Learning
  DISCOVERY_FAILED: "DISCOVERY_FAILED",
  // Structured output
  STRUCTURED_OUTPUT_PARSE_FAILED: "STRUCTURED_OUTPUT_PARSE_FAILED",
  // Loop
  INVALID_TRANSITION: "INVALID_TRANSITION",
  EVENT_BUS_ERROR: "EVENT_BUS_ERROR",
  // Privacy
  PRIVACY_CONSENT_MISSING: "PRIVACY_CONSENT_MISSING",
  RETENTION_ENFORCEMENT_FAILED: "RETENTION_ENFORCEMENT_FAILED",
  // Approval
  APPROVAL_NOT_FOUND: "APPROVAL_NOT_FOUND",
  APPROVAL_ALREADY_RESOLVED: "APPROVAL_ALREADY_RESOLVED",
  APPROVAL_MAX_ESCALATIONS: "APPROVAL_MAX_ESCALATIONS",
  // Calendar
  CALENDAR_SYNC_FAILED: "CALENDAR_SYNC_FAILED",
  CALENDAR_PROVIDER_ERROR: "CALENDAR_PROVIDER_ERROR",
  CALENDAR_EVENT_NOT_FOUND: "CALENDAR_EVENT_NOT_FOUND",
  // Home Automation
  HA_UNAVAILABLE: "HA_UNAVAILABLE",
  HA_ENTITY_NOT_FOUND: "HA_ENTITY_NOT_FOUND",
  HA_SCENE_NOT_FOUND: "HA_SCENE_NOT_FOUND",
  HA_SERVICE_FAILED: "HA_SERVICE_FAILED",
  HA_POLICY_DENIED: "HA_POLICY_DENIED",
  // WhatsApp
  WHATSAPP_API_ERROR: "WHATSAPP_API_ERROR",
  WHATSAPP_WEBHOOK_INVALID: "WHATSAPP_WEBHOOK_INVALID",
  WHATSAPP_RATE_LIMITED: "WHATSAPP_RATE_LIMITED",
  WHATSAPP_MEDIA_ERROR: "WHATSAPP_MEDIA_ERROR",
  // Email
  EMAIL_IMAP_ERROR: "EMAIL_IMAP_ERROR",
  EMAIL_SMTP_ERROR: "EMAIL_SMTP_ERROR",
  EMAIL_PARSE_ERROR: "EMAIL_PARSE_ERROR",
  EMAIL_AUTH_ERROR: "EMAIL_AUTH_ERROR",
  // LLM providers
  LLM_RESPONSE_INVALID: "LLM_RESPONSE_INVALID",
  // Wyoming
  WYOMING_CONNECTION_REJECTED: "WYOMING_CONNECTION_REJECTED",
  WYOMING_PROTOCOL_ERROR: "WYOMING_PROTOCOL_ERROR",
  WYOMING_HANDLER_FAILED: "WYOMING_HANDLER_FAILED",
  // Browser
  BROWSER_NOT_AVAILABLE: "BROWSER_NOT_AVAILABLE",
  BROWSER_NAVIGATION_FAILED: "BROWSER_NAVIGATION_FAILED",
  BROWSER_ACTION_FAILED: "BROWSER_ACTION_FAILED",
  BROWSER_NOT_STARTED: "BROWSER_NOT_STARTED",
  // General
  INVALID_INPUT: "INVALID_INPUT",
  INVALID_STATE: "INVALID_STATE",
  DEPENDENCY_MISSING: "DEPENDENCY_MISSING",
  TIMEOUT: "TIMEOUT",
  CIRCUIT_OPEN: "CIRCUIT_OPEN",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export interface EidolonError {
  readonly code: ErrorCode;
  readonly message: string;
  readonly cause?: unknown;
  readonly timestamp: number;
}

export function createError(code: ErrorCode, message: string, cause?: unknown): EidolonError {
  return {
    code,
    message,
    cause,
    timestamp: Date.now(),
  };
}
